## Dockerfile
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80" ## Map the port 8080 of the host to the port 80 of the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf ## Mount the nginx.conf file to the container
    depends_on:
      - node_app
  node_app:
    build: .
    volumes:
      - .:/app ## Mount the current directory to the /app directory of the container
